---
# Advanced Example Playbook for "sh" Ansible Module

- name: Test Play
  hosts: ubuntu, centos, controller
  become: true
  tasks:

###################################### Example 1

    - name: Testing RegExp search with operators # if condition-cmd-stdout = RegExp-match-of /eth[0-9]/ AND condition-cmd-rc > 0
      sh:
        cmd: 'echo "Execute some commands"'
        condition: 'ifconfig -a'
        lang: bash
        regexp: True
        if_stdout: 'eth[0-9]'
        if_stdout_operator: '='   # "=" must be in quotes
        if_rc: 0
        if_rc_operator: '>'
      register: debug

    - debug:
        var: debug

###################################### Example 2


    - name: Testing rc operators # Execute the command if condition-command-rc < 1
      sh:
        cmd: 'echo "Execute some commands"'
        condition: 'ifconfig -a'
        lang: bash
        if_rc: 1
        if_rc_operator: '<'
      register: debug

    - debug:
        var: debug