---
# Sample Playbook for "sh" Ansible Module

- name: Test Play
  hosts: ubuntu, centos, controller
  become: true
  tasks:

###################################### Example 1

    - name: normal # Execute the command without condition
      sh:
        cmd: 'hostname'
      register: debug

    - debug:
        var: debug


###################################### Example 2

    - name: run command basd of the "stdout" of another command
      sh:
        cmd: 'hostnamectl'
        condition: 'hostname'
        lang: bash
        if_stdout: 'ansible'
      register: debug

    - debug:
        var: debug


###################################### Example 3

    - name: run command based of the "rc" of another command #  multi line
      sh:
        cmd: |
          export pass='password'
          export users_file=/root/users.txt
          echo 'user-test' > $users_file

              if [ -f $1 ] ; then
                  for i in $( cat /root/users.txt ); do
                     useradd "$i"
                     echo "User $i created successfully"
                     echo $pass | passwd "$i" --stdin
                  done
              else
                  echo "Input is NOT a file"
              fi
        condition: 'cat /etc/passwd | grep user-test'
        lang: bash
        if_rc: 1
      register: multi_line

    - debug:
        var: multi_line


###################################### Example 4


    - name: run command based on Python code # if condition-command-stdout = 'open'
      sh:
        cmd: echo 'Execute some commands '
        condition: |
          import socket
          sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          result = sock.connect_ex(('127.0.0.1',22))
          if result == 0:
             print "open"
          else:
             print "not-open"
          sock.close()
        lang: python
        if_stdout: 'open'
      register: test_python

    - debug:
        var: test_python


###################################### Example 5


    - name: run command based on Python code 2 # if condition-command-rc = 1
      sh:
        cmd: echo 'Execute some commands '
        condition: |
          import socket
          sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          result = sock.connect_ex(('127.0.0.1',24))
          if result == 0:
             print "open"
             sock.close()
          else:
             print "not-open"
             sock.close()
             exit(1)
        lang: python
        if_rc: 1
      register: test_python2

    - debug:
        var: test_python2
