---
# Sample Playbook for "sh" Ansible Module

- name: Test Play
  hosts: localhost, ubuntu, controller
  become: true
  tasks:
    - name: run command basd of the "stdout" of another command
      sh:
        cmd: 'hostname'
      register: test_sh

    - debug:
        var: test_sh


    - name: run command based of the "rc" of another command --  multi line
      sh:
        cmd: |
          export pass='password'
          export users_file=/root/users.txt
          echo 'user-test' > $users_file

              if [ -f $1 ] ; then
                  for i in $( cat /root/users.txt ); do
                     useradd "$i"
                     echo "User $i created successfully"
                     echo $pass | passwd "$i" --stdin
                  done
              else
                  echo "Input is NOT a file"
              fi
        condition: 'cat /etc/passwd | grep user-test'
        lang: bash
        if_rc: 1
      register: multi_line

    - debug:
        var: multi_line

    - name: run command based on Python code
      sh:
        cmd: echo 'Execute some commands '
        condition: |
          import socket
          sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          result = sock.connect_ex(('127.0.0.1',22))
          if result == 0:
             print "open"
          else:
             print "not-open"
          sock.close()
        lang: python
        if_stdout: 'open'
      register: test_python

    - debug:
        var: test_python

    - name: run command based on Python code 2
      sh:
        cmd: echo 'Execute some commands '
        condition: |
          import socket
          sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          result = sock.connect_ex(('127.0.0.1',24))
          if result == 0:
             print "open"
             sock.close()
          else:
             print "not-open"
             sock.close()
             exit(1)
        lang: python
        if_rc: 1
      register: test_python2

    - debug:
        var: test_python2
