---
# Sample Playbook for "sh" Ansible Module

- name: Test Play
  hosts: localhost, ubuntu, controller
  become: true
  tasks:
    - name: run command based on Python code
      sh:
        cmd: echo 'Execute some commands '
        condition: |
          import socket
          sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          result = sock.connect_ex(('127.0.0.1',24))
          if result == 0:
             print "open"
             sock.close()
          else:
             print "not-open"
             sock.close()
             exit(1)
        lang: python
        if_rc: 1
        if_stdout: 'not-open'
      register: test_python

    - debug:
        var: test_python



